// src/components/FeedbackModal/FeedbackModal.tsx
/**
 * Feedback Modal Component
 */

import React, { useEffect, useRef } from 'react';
import { useFeedback } from '../../context/FeedbackContext';
import { NPSRating } from './NPSRating';
import { saveLastNPSSubmission, shouldResetNPS } from '../../utils/storage';
import { AnnotationList } from './AnnotationList';
import type { JiraConfig, ElasticConfig } from '../../types';
import { calculateNPSSegment } from '../../utils/validation';
import { useModalSubmission } from '../../hooks/useModalSubmission';
import { MessageSquare } from 'lucide-react';
import styles from './FeedbackModal.module.css';

interface FeedbackModalProps {
  jiraConfig?: JiraConfig;
  elasticConfig?: ElasticConfig;
  onSubmit?: (feedback: any) => void;
  onError?: (error: Error) => void;
  requireCategory?: boolean;
  enableNPS?: boolean;
  getUserId?: () => string | null;
  appVersion?: string;
  customContext?: Record<string, any>;
  screenshotQuality?: number;
}

const TOTAL_STEPS = 3; // Step 1: Review, Step 2: NPS (after submit), Step 3: Confirmation

// Validation helper for each step
function validateStep(
  step: number,
  state: any,
  requireCategory: boolean,
  enableNPS: boolean
): { valid: boolean; errors: string[] } {
  const errors: string[] = [];

  if (step === 1) {
    // Step 1: At least one annotation required
    if (state.annotations.length === 0) {
      errors.push('Please add at least one annotation');
    }
  }

  if (step === 2 && enableNPS) {
    // Step 2: NPS is optional, no validation needed
    return { valid: true, errors: [] };
  }

  return {
    valid: errors.length === 0,
    errors,
  };
}

export function FeedbackModal({
  jiraConfig,
  elasticConfig,
  onSubmit,
  onError,
  requireCategory = false,
  enableNPS = true,
  getUserId,
  appVersion,
  customContext,
  screenshotQuality = 0.8,
}: FeedbackModalProps) {
  const {
    state,
    setModalOpen,
    setCurrentStep,
    reset,
    dispatch,
    setToolbarExpanded,
    setToolMode,
  } = useFeedback();
  const modalRef = useRef<HTMLDivElement>(null);
  const previousFocusRef = useRef<HTMLElement | null>(null);

  const {
    isSubmitting,
    isSuccess,
    errors,
    isGeneratingScreenshots,
    handleSubmit,
    setErrors,
    setIsSuccess,
  } = useModalSubmission({
    jiraConfig,
    elasticConfig,
    onSubmit,
    onError,
    getUserId,
    appVersion,
    customContext,
    screenshotQuality,
    category: state.category,
    severity: state.severity,
    npsScore: state.npsScore ?? 0,
    npsSegment: calculateNPSSegment(state.npsScore ?? 0),
    autoGenerateScreenshots: state.currentStep === 1,
  });

  // Check if NPS should be reset when modal opens (90 days have passed)
  useEffect(() => {
    if (state.isModalOpen && enableNPS && shouldResetNPS() && state.npsScore !== null) {
      // Reset NPS score if 90 days have passed
      dispatch({ type: 'SET_NPS_SCORE', payload: null });
    }
  }, [state.isModalOpen, enableNPS, state.npsScore, dispatch]);

  // Focus trap and close toolbar when modal opens
  useEffect(() => {
    if (!state.isModalOpen) return;

    previousFocusRef.current = document.activeElement as HTMLElement;
    
    // Get all focusable elements within the modal
    const getFocusableElements = (): HTMLElement[] => {
      if (!modalRef.current) return [];
      
      const selector = 'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])';
      return Array.from(modalRef.current.querySelectorAll<HTMLElement>(selector)).filter(
        (el) => !el.hasAttribute('disabled') && !el.hasAttribute('aria-hidden')
      );
    };

    // Focus first focusable element
    const focusableElements = getFocusableElements();
    if (focusableElements.length > 0) {
      focusableElements[0].focus();
    } else {
      modalRef.current?.focus();
    }
    
    // Close toolbar when modal opens
    setToolbarExpanded(false);

    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        handleClose();
        return;
      }

      // Focus trap: Tab and Shift+Tab
      if (e.key === 'Tab') {
        const focusableElements = getFocusableElements();
        if (focusableElements.length === 0) {
          e.preventDefault();
          return;
        }

        const firstElement = focusableElements[0];
        const lastElement = focusableElements[focusableElements.length - 1];
        const currentIndex = focusableElements.indexOf(document.activeElement as HTMLElement);

        if (e.shiftKey) {
          // Shift+Tab: move backwards
          if (currentIndex <= 0 || document.activeElement === firstElement) {
            e.preventDefault();
            lastElement.focus();
          }
        } else {
          // Tab: move forwards
          if (currentIndex === focusableElements.length - 1 || document.activeElement === lastElement) {
            e.preventDefault();
            firstElement.focus();
          }
        }
      }
    };

    document.addEventListener('keydown', handleKeyDown);
    document.body.style.overflow = 'hidden';

    return () => {
      document.removeEventListener('keydown', handleKeyDown);
      document.body.style.overflow = '';
      previousFocusRef.current?.focus();
    };
  }, [state.isModalOpen, handleClose, setToolbarExpanded]);

  const handleClose = () => {
    // TODO: Check for unsaved changes
    setModalOpen(false);
    setCurrentStep(1);
    setErrors([]);
    setIsSuccess(false);
  };

  const handleNext = () => {
    // Validate current step before proceeding
    const validation = validateStep(
      state.currentStep,
      state,
      requireCategory,
      enableNPS
    );

    if (!validation.valid) {
      setErrors(validation.errors);
      return;
    }

    setErrors([]);
    if (state.currentStep < TOTAL_STEPS) {
      setCurrentStep(state.currentStep + 1);
    }
  };

  const handleSubmitStep = async () => {
    // Validate before submit (Step 1: Review annotations)
    const validation = validateStep(1, state, requireCategory, enableNPS);
    if (!validation.valid) {
      setErrors(validation.errors);
      return;
    }

    setErrors([]);
    await handleSubmit(() => validation.errors);
  };

  useEffect(() => {
    if (!isSuccess) return;

    if (enableNPS) {
      setCurrentStep(2);
    } else {
      setCurrentStep(3);
    }
  }, [isSuccess, enableNPS, setCurrentStep]);

  const progress = (state.currentStep / TOTAL_STEPS) * 100;

  return (
    <div
      className={styles.backdrop}
      onClick={handleClose}
      role="dialog"
      aria-modal="true"
      aria-labelledby="feedback-modal-title"
    >
      <div
        ref={modalRef}
        className={styles.modal}
        onClick={(e) => e.stopPropagation()}
        tabIndex={-1}
      >
        <div className={styles.header}>
          <div className={styles.headerLeft}>
            <MessageSquare size={20} className={styles.headerIcon} />
            <div>
              <h2 id="feedback-modal-title">Share Your Feedback</h2>
              <div className={styles.stepIndicator}>
                Step {state.currentStep} of {TOTAL_STEPS}
              </div>
            </div>
          </div>
          <button
            className={styles.closeButton}
            onClick={handleClose}
            aria-label="Close modal"
          >
            ×
          </button>
        </div>

        <div className={styles.progress}>
          <div
            className={styles.progressBar}
            style={{ width: `${progress}%` }}
          />
        </div>

        <div className={styles.content}>
          {/* Step 1: Review & Edit Annotations */}
          {state.currentStep === 1 && (
            <div>
              <div className={styles.stepHeader}>
                <h3>Review Annotations</h3>
                <p className={styles.stepDescription}>
                  Review and edit your annotations. At least one annotation is required.
                </p>
              </div>
              {isGeneratingScreenshots && (
                <div className={styles.screenshotLoading}>
                  <div className={styles.loadingSpinner}></div>
                  <p>Generating screenshots...</p>
                </div>
              )}
              <AnnotationList />
              <div className={styles.addAnotherContainer}>
                <button
                  className={styles.addAnotherButton}
                  onClick={() => {
                    setModalOpen(false);
                    setToolbarExpanded(true);
                    setToolMode('element');
                  }}
                  type="button"
                >
                  + Add Another Annotation
                </button>
              </div>
            </div>
          )}
          
          {/* Step 2: NPS (after submission) */}
          {state.currentStep === 2 && enableNPS && (
            <div>
              <div className={styles.stepHeader}>
                <h3>How satisfied are you with this application?</h3>
                <p className={styles.stepDescription}>
                  Your feedback has been submitted! This step is optional.
                </p>
              </div>
              <NPSRating 
                onNext={() => {
                  // Save NPS submission timestamp when user provides a score
                  if (state.npsScore !== null) {
                    saveLastNPSSubmission();
                  }
                  // Move to confirmation after NPS
                  setCurrentStep(3);
                }} 
                onSkip={() => {
                  // Skip NPS and go to confirmation
                  setCurrentStep(3);
                }} 
              />
            </div>
          )}
          
          {/* Step 3: Confirmation */}
          {state.currentStep === 3 && (
            <div className={styles.confirmation}>
              <div className={styles.confirmationIcon}>✓</div>
              <h3>Thank you for your feedback!</h3>
              <p>Your feedback has been submitted successfully.</p>
              <button
                className={styles.submitAnotherButton}
                onClick={() => {
                  reset();
                  setIsSuccess(false);
                  setErrors([]);
                  setModalOpen(false);
                  setToolbarExpanded(true);
                  setToolMode('element');
                }}
                type="button"
              >
                Submit Another
              </button>
            </div>
          )}
          
          {/* Error messages */}
          {errors.length > 0 && (
            <div 
              className={styles.errorContainer} 
              role="alert"
              aria-live="assertive"
              aria-atomic="true"
            >
              {errors.map((error, index) => (
                <div key={index} className={styles.errorMessage}>
                  {error}
                </div>
              ))}
            </div>
          )}
        </div>

        <div className={styles.footer}>
          {state.currentStep === 1 && (
            <>
              <div className={styles.spacer} />
              <button
                className={styles.buttonPrimary}
                onClick={handleSubmitStep}
                type="button"
                disabled={isSubmitting || state.annotations.length === 0}
              >
                {isSubmitting ? 'Submitting...' : 'Submit'}
              </button>
            </>
          )}
          {state.currentStep === 2 && enableNPS && (
            <>
              <div className={styles.spacer} />
              <button
                className={styles.buttonPrimary}
                onClick={handleNext}
                type="button"
              >
                Continue
              </button>
            </>
          )}
          {state.currentStep === 3 && (
            <>
              <div className={styles.spacer} />
              <button
                className={styles.buttonPrimary}
                onClick={() => {
                  reset();
                  setIsSuccess(false);
                  setErrors([]);
                  setModalOpen(false);
                }}
                type="button"
              >
                Close
              </button>
            </>
          )}
        </div>
      </div>
    </div>
  );
}

// angular/src/components/feedback-modal.ts
import { Component, inject, input, output, effect, computed } from '@angular/core';
import { FeedbackStore } from '../store/feedback.store';
import { SubmissionService } from '../services/submission.service';
import { StorageService } from '../services/storage.service';
import { BaseModalComponent } from './base-modal';
import { AnnotationListComponent } from './annotation-list';
import { NpsRatingComponent } from './nps-rating';
import type { FeedbackData } from '../models/feedback.model';
import { LucideAngularModule, MessageSquare } from 'lucide-angular';

const TOTAL_STEPS = 3;

@Component({
  selector: 'fb-feedback-modal',
  standalone: true,
  imports: [
    BaseModalComponent,
    AnnotationListComponent,
    NpsRatingComponent,
    LucideAngularModule,
  ],
  template: `
    <fb-base-modal
      [isOpen]="store.isModalOpen()"
      title="Share Your Feedback"
      ariaLabelledBy="feedback-modal-title"
      (closed)="handleClose()"
    >
      <lucide-icon modalIcon name="message-square" [size]="20" class="text-primary" />

      <!-- Step indicator + progress -->
      <div class="mb-4">
        <div class="mb-2 text-xs text-muted-foreground">
          Step {{ store.currentStep() }} of {{ totalSteps }}
        </div>
        <div class="h-1.5 w-full overflow-hidden rounded-full bg-muted">
          <div
            class="h-full rounded-full bg-primary transition-all"
            [style.width.%]="progress()"
          ></div>
        </div>
      </div>

      <!-- Step content -->
      @switch (store.currentStep()) {
        @case (1) {
          <div class="space-y-4">
            <div>
              <h3 class="text-sm font-semibold text-foreground">Review Annotations</h3>
              <p class="mt-1 text-xs text-muted-foreground">
                Review and edit your annotations. At least one annotation is required.
              </p>
            </div>
            @if (submission.isGeneratingScreenshots()) {
              <div class="flex items-center gap-2 text-sm text-muted-foreground">
                <div class="size-4 animate-spin rounded-full border-2 border-muted-foreground border-t-transparent"></div>
                <p>Generating screenshots...</p>
              </div>
            }
            <fb-annotation-list />
            <button
              class="inline-flex items-center rounded-md border border-dashed border-border px-3 py-2 text-sm text-muted-foreground hover:bg-accent hover:text-accent-foreground"
              (click)="handleAddAnnotation()"
              type="button"
            >
              + Add Another Annotation
            </button>
          </div>
        }
        @case (2) {
          <div class="space-y-4">
            <div>
              <h3 class="text-sm font-semibold text-foreground">How satisfied are you with this application?</h3>
              <p class="mt-1 text-xs text-muted-foreground">
                Your feedback has been submitted! This step is optional.
              </p>
            </div>
            <fb-nps-rating
              (next)="handleNPSNext()"
              (skip)="store.setCurrentStep(3)"
            />
          </div>
        }
        @case (3) {
          <div class="flex flex-col items-center py-8 text-center">
            <div class="mb-4 flex size-12 items-center justify-center rounded-full bg-green-500/20 text-green-500 text-2xl">
              &#10003;
            </div>
            <h3 class="text-lg font-semibold text-foreground">Thank you for your feedback!</h3>
            <p class="mt-1 text-sm text-muted-foreground">Your feedback has been submitted successfully.</p>
            <button
              class="mt-4 inline-flex items-center justify-center rounded-md border border-border px-4 py-2 text-sm font-medium text-foreground hover:bg-accent hover:text-accent-foreground"
              (click)="handleSubmitAnother()"
              type="button"
            >
              Submit Another
            </button>
          </div>
        }
      }

      <!-- Errors -->
      @if (submission.errors().length > 0) {
        <div class="mt-4 rounded-md border border-destructive/30 bg-destructive/10 p-3" role="alert" aria-live="assertive">
          @for (error of submission.errors(); track error) {
            <div class="text-sm text-destructive">{{ error }}</div>
          }
        </div>
      }

      <!-- Footer -->
      <div modalFooter>
        @switch (store.currentStep()) {
          @case (1) {
            <div class="flex-1"></div>
            <button
              class="inline-flex items-center justify-center rounded-md bg-primary px-5 py-2 text-sm font-medium text-primary-foreground hover:bg-primary/90 disabled:opacity-50"
              (click)="handleSubmitStep()"
              type="button"
              [disabled]="submission.isSubmitting() || store.annotations().length === 0"
            >
              {{ submission.isSubmitting() ? 'Submitting...' : 'Submit' }}
            </button>
          }
          @case (2) {
            <div class="flex-1"></div>
            <button
              class="inline-flex items-center justify-center rounded-md bg-primary px-5 py-2 text-sm font-medium text-primary-foreground hover:bg-primary/90"
              (click)="store.setCurrentStep(3)"
              type="button"
            >
              Continue
            </button>
          }
          @case (3) {
            <div class="flex-1"></div>
            <button
              class="inline-flex items-center justify-center rounded-md bg-primary px-5 py-2 text-sm font-medium text-primary-foreground hover:bg-primary/90"
              (click)="handleFinalClose()"
              type="button"
            >
              Close
            </button>
          }
        }
      </div>
    </fb-base-modal>
  `,
})
export class FeedbackModalComponent {
  protected readonly store = inject(FeedbackStore);
  protected readonly submission = inject(SubmissionService);
  private readonly storage = inject(StorageService);

  readonly enableNPS = input<boolean>(true);
  readonly requireCategory = input<boolean>(false);
  readonly onSubmit = input<((feedback: FeedbackData) => void) | undefined>();
  readonly onError = input<((error: Error) => void) | undefined>();
  readonly getUserId = input<(() => string | null) | undefined>();
  readonly appVersion = input<string | undefined>();
  readonly customContext = input<Record<string, unknown> | undefined>();
  readonly screenshotQuality = input<number>(0.8);
  readonly addAnnotationRequested = output<void>();

  protected readonly totalSteps = TOTAL_STEPS;
  protected readonly progress = computed(
    () => (this.store.currentStep() / TOTAL_STEPS) * 100,
  );

  constructor() {
    effect(() => {
      if (this.submission.isSuccess()) {
        if (this.enableNPS()) {
          this.store.setCurrentStep(2);
        } else {
          this.store.setCurrentStep(3);
        }
      }
    });
  }

  protected handleClose(): void {
    this.store.setModalOpen(false);
    this.store.setCurrentStep(1);
    this.submission.setErrors([]);
    this.submission.setIsSuccess(false);
  }

  protected async handleSubmitStep(): Promise<void> {
    if (this.store.annotations().length === 0) {
      this.submission.setErrors(['Please add at least one annotation']);
      return;
    }

    await this.submission.submit({
      category: this.store.category(),
      severity: this.store.severity(),
      npsScore: this.store.npsScore() ?? 0,
      npsSegment: this.store.npsSegment() ?? 'detractor',
      getUserId: this.getUserId(),
      appVersion: this.appVersion(),
      customContext: this.customContext(),
      screenshotQuality: this.screenshotQuality(),
      onSubmit: this.onSubmit(),
      onError: this.onError(),
    });
  }

  protected handleNPSNext(): void {
    if (this.store.npsScore() !== null) {
      this.storage.saveLastNPSSubmission();
    }
    this.store.setCurrentStep(3);
  }

  protected handleAddAnnotation(): void {
    this.store.setModalOpen(false);
    this.store.setToolbarExpanded(true);
    this.store.setToolMode('element');
    this.addAnnotationRequested.emit();
  }

  protected handleSubmitAnother(): void {
    this.store.reset();
    this.submission.setIsSuccess(false);
    this.submission.setErrors([]);
    this.store.setModalOpen(false);
    this.store.setToolbarExpanded(true);
    this.store.setToolMode('element');
  }

  protected handleFinalClose(): void {
    this.store.reset();
    this.submission.setIsSuccess(false);
    this.submission.setErrors([]);
    this.store.setModalOpen(false);
  }
}
